service: bitpazaar-lambdas
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  environment:
    STAGE: ${opt:stage, 'mainnet'}
package:
  individually: true
functions:
  generateBitPazaarAccessKey:
    handler: lambdas/generateBitPazaarAccessKey.handler
  getNftsByOwner:
    handler: lambdas/getNftsByOwner.handler
